name: Test code
on:
  push:
    branches:
      - main

jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
      - uses: conda-incubator/setup-miniconda@v3
        with:
          channels: acellera,conda-forge,defaults
          python-version: ${{ matrix.python-version }}
      - name: Lint with flake8
        run: 'pip install flake8==7.1.2 coverage

          # stop the build if there are Python syntax errors or undefined names

          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars
          wide

          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

          '
      - id: measurement-4
        name: Record Measurement After Lint with flake8
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Lint with flake8
          task: get-measurement
      - if: ${{ matrix.os != 'windows-2022' }}
        name: Install blast for OPM tests
        run: conda install -c bioconda blast -y -q
      - id: measurement-6
        name: Record Measurement After Install blast for OPM tests
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install blast for OPM tests
          task: get-measurement
      - name: Install moleculekit
        run: 'pip install build pytest pytest-xdist

          python -m build

          pip install dist/moleculekit-*.whl

          '
      - id: measurement-8
        name: Record Measurement After Install moleculekit
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install moleculekit
          task: get-measurement
      - name: List conda environment
        run: conda list
      - id: measurement-10
        name: Record Measurement After List conda environment
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: List conda environment
          task: get-measurement
      - env:
          LOCAL_PDB_REPO: ./tests/pdb/
          SKIP_SPEED_TESTS: true
        name: Test
        run: 'pytest -n auto ./tests/ --durations=20

          '
      - id: measurement-12
        name: Record Measurement After Test
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Test
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - macos-13
          - windows-2022
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
